간편식 자동 생성
dimigoin/dimigoin-back-v3 pull request #140
Opened 2022-08-11 10:43 UTC by omh02033

2022-08-11 13:09 UTC, doch2 commented
학생들이 신청하는 API도 추가될때 코드리뷰 진행하겠습니다!

2022-08-11 14:37 UTC, omh02033 commented
- [ ] 하루에 한 학년에 17명 제한
- [ ] 각각 최대 50명
- [ ] 월,화요일만 신청 가능하게
- [ ] 간편식 체크인
- [ ] 일주일에 두 번 이상 안먹으면 다음주 신청기회 박탈

@doch2 확인해주세용

2022-08-11 15:15 UTC, doch2 commented
네네 간편식 관련 API는 일단 위에 작성해주신 투두 리스트 정도만 지켜서 만들어주시면 될 것 같습니당

마지막 체크리스트의 '일주일에 두 번 이상 안먹으면 다음주 신청기회 박탈'은 다음주가 아니라 다음 번에 신청했을 때 거절하는 방향으로 개발해야 합니다! 투두리스트 수정해주세요

2022-08-12 13:29 UTC, doch2 requested changes

2022-08-12 13:29 UTC, doch2 commented on src/resources/dalgeurak.ts
> +    misu: '선색',
선색 -> 선식 오타입니당

2022-08-12 13:29 UTC, doch2 commented on src/resources/dalgeurak.ts
> +      if (breakfastCheckin.filter((s) => s === student).length <= 3) // 일주일에 간편식 식사수가 3회 이하일 때 (평일 공휴일 고려하지 않음.)
공휴일도 고려해서 로직 다시 짜주세요!

아니면 일주일에 3번 이상 먹을때 작동되는게 아니고 2번 이상 안먹을 때로 수정하셔도 괜찮습니당

2022-08-12 13:29 UTC, doch2 commented on src/resources/dalgeurak.ts
> +      if (dinnerCheckin.filter((s) => s === student).length <= 3) { await new ConvenienceDepriveModel({
위에 점심부분 코드 Comment와 같습니다

2022-08-17 07:05 UTC, merged