feat : add remove notice controller
dimigoin/dimigoin-back-v3 pull request #39
Opened 2021-02-12 14:39 UTC by rycont

공지사항을 삭제하는 라우트입니다

2021-02-12 15:34 UTC, uhmseohun requested changes
공지사항 추가 엔드포인트에 학생 권한도 들어간 것 같아요

2021-02-12 15:48 UTC, rycont commented
프엔 테스트하던 코드가 그대로 들어갔었네요ㅜ 수정했습니다!

2021-02-12 16:09 UTC, uhmseohun approved these changes

2021-02-12 16:09 UTC, uhmseohun commented
좋아욥 !!

2021-02-13 09:06 UTC, uhmseohun commented
음 그냥 제가 머지하겠습니당

2021-02-13 09:06 UTC, merged