Dets service
dimigoin/dimigoin-back-v3 pull request #9
Opened 2020-12-06 22:24 UTC by cokia

[GET] /dets => Dets 리스트 반환

[GET] /dets/:detsId => 상세 Dets 정보 반환

[POST] /dets/ => dets 생성

[POST] /dets/apply/:detsId -> Dets 신청

[PATCH] /dets/:detsId => Dets 수정

2020-12-06 23:12 UTC, rycont requested changes
@cokia 코드리뷰 했습니다! 확인해주세요 👍

2020-12-06 23:12 UTC, rycont commented on src/controllers/dets.ts
> +    return true;
`return model.user.length >= model.maxCount`

2020-12-06 23:12 UTC, rycont commented on src/controllers/dets.ts
> +  }
`id`로 같은 doc을 찾는 과정을 두번 수행하고 있는데, isMax를 인원초과여부 뿐만 아니라 도큐먼트로써 활용할수는 없을까요?

2020-12-06 23:12 UTC, rycont commented on src/interfaces/dets.ts
> +}
마지막줄 빈칸 넣어주세요 :)

2020-12-06 23:12 UTC, rycont commented on src/models/dets.ts
> +  targetGrade: Type.number({ required: true }), // add grade validation
[GradeValue](https://github.com/dimigoin/dimigoin-back-v3/blob/31f03dbb83b5000329d3f0e0ebda6c1d38c71f01/src/types/index.ts#L32) 값이 있는걸로 알고있어요.

2020-12-06 23:12 UTC, rycont commented on src/models/dets.ts
> +  targetGrade: Type.number({ required: true }), // add grade validation
Enum으로 박는게 좋아보입니다!

2021-02-07 07:33 UTC, cokia commented
deprecated

2021-02-07 07:33 UTC, closed without merging